### ISSUE TITLE
Unable To Sign In

### ISSUE THREAD

**Issue by KensonPlayz** [DaryeDev/LootsTools#2]
I've tried with YouTube and Twitch sign ins, get this on both:
![image](https://user-images.githubusercontent.com/74943224/134613397-c3a917a5-aacc-4ecc-bb07-20acb9dab3f1.png)

**Comment by DaryeDev** [comment]
The sign-in process is somewhat fragile, and I'm currently thinking and working on a more stable way of logging in. I'm now working on a browser extension and will write about it and update Loot's Tools when I finish it.

As a temporal and manual solution, you could create a file on `%APPDATA%/DysonTools/LootsTools` called "streamlootsLogin.yml". Inside of it, write "`token: `", followed by your authToken, both without quotation marks.

To get the authToken, you'll need to go to [streamloots.com](https://streamloots.com), login, press F12, and go to the Console. Then write `window.__INITIAL_STATE__.auth.authToken` and press ENTER. 

Currently, there's no better way to log in, but, as said earlier, I'm working on a Browser Extension to log in directly from the Browser.

**Comment by KensonPlayz** [comment]
I setup the token as:
token:'tokenidhere'

but its still giving the same error. Do I need to remove the ' on the ends?

Edit: Tried with and without the ' quotes, same on both ends.
![image](https://user-images.githubusercontent.com/74943224/134741970-663939da-df83-41a8-a852-6dd03daf4ae9.png)
These are the two files in the appdata folder.

**Comment by DaryeDev** [comment]
It seems you have to put a space between 'token:' and the token itself. I'd put it on the reply, but it's easy not to notice hehe.

Just put a space between the ":" and your token, it should work now.

**Comment by DaryeDev** [comment]
If your issue was fixed, I'll close this issue. 
Extensions for Chrome and Firefox to log in from the browser will be released soon to their respective stores, so people with this issue can login with them.
