### ISSUE TITLE
Twitch Extension Fails To Load

### ISSUE THREAD

**Issue by SighFye** [DaryeDev/LootsTools#4]
![image](https://user-images.githubusercontent.com/6553991/156259142-01755ffa-c61a-4f74-a0f4-ccfd62bf2fd3.png)
When I reload my extensions after a successful installation of the Twitch extension, I see the message in the console window.

**Comment by DaryeDev** [comment]
This issue was because the dependencies were loaded on Loot's Tools' initial boot, on v2.4.5 this is fixed, and now they are reloaded on EXtension load. 

Closing issue.
