### ISSUE TITLE
Desconexión LTEX for Twitch

### ISSUE THREAD

**Issue by mimundodisney** [DaryeDev/LootsTools#5]
Se desconecta la extensión de Twitch y los mensajes no aparecen en el chat. Con streamloots no hay problema.

![Captura de pantalla (178)](https://user-images.githubusercontent.com/122322846/211423954-d16062ed-b35b-42c3-b69e-eff34e1ea2f8.png)

**Comment by DaryeDev** [comment]
En la UI, ve a la página de la extensión de Twitch y resetea tokens. 

Solucionará tus problemas con la extensión de Twitter un 99% de las veces jj

**Comment by DaryeDev** [comment]
Cierro este problema.
